server:
  port: 9999
  path: /hello

person:
  name: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1, k2: 12} #字符串默认可以不添加引号
  lists:
  - lisi
  - zhaoliu
  dog:
    name: 小狗
    age: 12
  gender: 男,女
# debug: true