server:
  port: 9999

  #sping-getway配置（方式一）

spring:
  cloud:
    gateway:
      routes:
      - id: tongjian_route
        uri: http://www.tongjian.org:9999/
        predicates:
        - Path=/tongjian

#spring.route.path: /baidu
#spring.route.uri: www.baid.com

#日志等级配置
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
