server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

spring.druid

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.spring.example.domain  # 注意：对应实体类的路径
  type-handlers-package: com.example.spring.mybatis.config  #handler的包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句到控制台

################txMapper配置####
#mybatis:
#  mapper-locations: classpath:mapper/*.xml #定义xml文件位置，不是必须的，如果需要在xml写sql请配置此选项
#  type-aliases-package: com.gogle.mgt.domain  # 注意：对应实体类的路径
mapper:
  mappers: com.example.spring.mybatis.txMapper.BaseMapper #通用基类配置
  identity: MYSQL
  notEmpty: false