server:
  port: 8082

dubbo:
  application:
    name: dubbo-provider

  registry:
    register: true
    address: 127.0.0.1
    port: 2181

  protocol:
    name: dubbo

  scan:
    base-packages: com.example.spring.dubbo.provider.provider
