spring:
  application:
    name: spring-elasticsearch
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

server:
  port: 9990
