# 数据源配置
dataSources:
  ds0: !!org.apache.commons.dbcp.BasicDataSource # 这里是强转转换
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds0
    username: root
    password:
  ds1: !!org.apache.commons.dbcp.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds1
    username: root
    password:

# 表的配置  (4点)
tables:
  t_order: # 逻辑表
    actualDataNodes: ds${0..1}.t_order${0..1} #真实节点
    databaseStrategy: # 数据库策略
      inline:         # 行表达式策略
        shardingColumn: user_id  # 分库键
        algorithmInlineExpression: ds${user_id % 2} # 分库的行表达式
    tableStrategy:
      inline:
        shardingColumn: order_id
        algorithmInlineExpression: t_order${order_id % 2}

  t_order_item:  # 逻辑表
    actualDataNodes: ds${0..1}.t_order_item${0..1}
    databaseStrategy:
      inline:
        shardingColumn: user_id
        algorithmInlineExpression: ds${user_id % 2}
    tableStrategy:
      inline:
        shardingColumn: order_id
        algorithmInlineExpression: t_order_item${order_id % 2}